configDependencies:
  '@pnpm/trusted-deps': '0.1.1+sha512-jI3PWNv2zCg9+KHI3qQTsa534c5nisZQrHFeWSyyHoUXcuzvjkXxQKPFLJ/qtNAF+PtKHDlRntO2aZKb3VDuHQ=='
  '@pnpm/better-defaults': '0.2.2+sha512-CxhLHXeW4XS/wludrcB9wgfVQmWYP0toYW5W700Aal5O6LK8qZmchvlCd/pRckBmAOWn8vT3AHokuyHvzLUv3A=='
overrides:
  '@swc/core': '1.9.3'
patchedDependencies:
  'eslint-plugin-react-perf@3.3.3': 'patches/eslint-plugin-react-perf@3.3.3.patch'
  'eslint-plugin-react-hooks@6.0.0-rc.1': 'patches/eslint-plugin-react-hooks@6.0.0-rc.1.patch'
  'typed-scss-modules@8.1.1': 'patches/typed-scss-modules@8.1.1.patch'
  'starknet@7.2.0': 'patches/starknet@7.2.0.patch'
onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@swc/core'
  - 'core-js'
  - 'esbuild'
  - 'javascript-obfuscator'
  - 'sharp'
  - '@tailwindcss/oxide'
  # - 'unrs-resolver'
onlyBuiltDependenciesFile: 'node_modules/.pnpm-config/@pnpm/trusted-deps/allow.json'
