/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PoolsIndexImport } from './routes/pools/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PoolsIndexRoute = PoolsIndexImport.update({
  id: '/pools/',
  path: '/pools/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/pools/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pools/': {
      id: '/pools/'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pools': typeof PoolsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pools': typeof PoolsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pools/': typeof PoolsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pools'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pools'
  id: '__root__' | '/' | '/pools/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoolsIndexRoute: typeof PoolsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoolsIndexRoute: PoolsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pools/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pools/": {
      "filePath": "pools/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
